spring.datasource.url=jdbc:postgresql://postgres:5432/m12_analytics
spring.datasource.username=patricia
spring.datasource.password=patricia
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.sql.init.mode=never

spring.kafka.bootstrap-servers=kafka:9092

# Topic subscribed by M12 (published by M06)
m12.kafka.topic.patch-events=m06-patch-events
