spring.application.name=m12-statistics-analytics
spring.profiles.active=dev

# spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080


springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html


server.port=${PORT:8084}

jwt.secret=${JWT_SECRET:patriciaSecretKeyForJwtValidation2025!}

services.profile.url=${SERVICES_PROFILE_URL}
services.campus-events.url=${SERVICES_CAMPUS_EVENTS_URL}
services.gamification.url=${SERVICES_GAMIFICATION_URL}
services.geolocation.url=${SERVICES_GEOLOCATION_URL}

spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME:guest}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:guest}
spring.rabbitmq.virtual-host=${RABBITMQ_VHOST:/}
spring.rabbitmq.ssl.enabled=${RABBITMQ_SSL:false}

rabbitmq.exchange.statistics=${RABBITMQ_EXCHANGE_STATISTICS:statistics.exchange}
rabbitmq.routing-key.report-ready=${RABBITMQ_RK_REPORT_READY:report.ready}
