spring.application.name=m12-statistics-analytics
spring.profiles.active=dev

# spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080


springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html


server.port=${PORT:8084}

jwt.secret=${JWT_SECRET:patriciaSecretKeyForJwtValidation2025!}

services.profile.url=${SERVICES_PROFILE_URL}
services.campus-events.url=${SERVICES_CAMPUS_EVENTS_URL}
services.gamification.url=${SERVICES_GAMIFICATION_URL}
services.geolocation.url=${SERVICES_GEOLOCATION_URL}
services.hangout.url=${SERVICES_HANGOUT_URL}
