spring.application.name=m12-statistics-analytics
spring.profiles.active=dev

spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

spring.kafka.consumer.group-id=m12-analytics-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.consumer.properties.spring.json.value.default.type=edu.eci.patriciaM12.infrastructure.adapters.messaging.dto.InboundPatchEventMessage

# Topic published by M06 — M12 subscribes here
m12.kafka.topic.patch-events=m06-patch-events


# spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080


springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html


server.port=${PORT:8080}

jwt.secret=${JWT_SECRET:patriciaSecretKeyForJwtValidation2025!}

services.profile.url=${SERVICES_PROFILE_URL}
services.campus-events.url=${SERVICES_CAMPUS_EVENTS_URL}
services.gamification.url=${SERVICES_GAMIFICATION_URL}
services.geolocation.url=${SERVICES_GEOLOCATION_URL}
