package edu.eci.patriciaM12.domain.model.enums;

/**
 * Enumerates the file formats in which an analytics report can be exported (RF-19).
 * Additional formats may be added in future iterations as new infrastructure adapters
 * are registered.
 *
 * <ul>
 *   <li>{@link #CSV} — comma-separated values; the default and currently only supported format</li>
 * </ul>
 */
public enum ExportFormat {

    /** Comma-separated values file, generated by the {@code CsvGeneratorPort} adapter. */
    CSV
}
